carts/urls.py
from django.urls import path
from carts import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>', views.add_cart, name="add_cart"),
    path('delete_cart_quantity/<int:cart_item_id>/<str:cart_id>', views.delete_cart_quantity, name="delete_cart_quantity"),
    path('remove_cart_item/<int:cart_item_id>/<str:cart_id>', views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout")

]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from greatkart import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('store/', include('store.urls'), name='store'),
    path('cart/' , include('carts.urls'), name = 'cart'),
    path('accounts/' , include('accounts.urls'), name = 'accounts'),
    path('order/', include('order.urls'), name='order')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

urlpatterns = [
    path('', views.show_store, name='store'),
    path('category/<slug:category_slug>/', views.show_store, name="product_by_category"),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name="product_detail"),
    path('search', views.search, name="search" )


]

carts/models.py
from django.db import models
from store.models import Product,VariationProduct
from accounts.models import Accounts
# Create your models here.
class Cart(models.Model):
    cart_id     = models.CharField(max_length=500, blank=True)
    created_at  = models.DateTimeField(auto_now_add=True)
    user        = models.ForeignKey(Accounts, on_delete=models.CASCADE, null = True)
    def __str__(self) -> str:
        return self.cart_id

class CartItem(models.Model):
    product     = models.ForeignKey(Product, on_delete = models.CASCADE)
    variation   = models.ManyToManyField(VariationProduct, blank=True)
    cart        = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity    = models.IntegerField()
    is_active   = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    product_name         = models.CharField(max_length = 200, unique= True)
    slug                = models.SlugField(max_length= 100, unique= True)
    description         = models.TextField(max_length=500, blank=True)
    price               = models.IntegerField()
    image               = models.ImageField(upload_to="photoes/products")
    stock               = models.IntegerField()
    is_available        = models.BooleanField(default = True)    
    category            = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at          = models.DateTimeField(auto_now_add= True)
    modefied_at         = models.DateTimeField(auto_now=True)

    def get_product_urls(self):
        return reverse('product_detail', args = [self.category.slug, self.slug,]) 


    def __str__(self):
        return self.product_name

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(category_name = 'color')
    def size(self):
        return super(VariationManager, self).filter(category_name = 'size')

category_name_select = (
    ('color', 'Color'),
    ('size', 'Size'),

)

class VariationProduct(models.Model):
    product             = models.ForeignKey(Product,on_delete=models.CASCADE)
    category_name       = models.CharField(max_length=100, choices=category_name_select)
    category_value      = models.CharField(max_length=100)
    is_active           = models.BooleanField(default=True)
    craeted_at          = models.DateTimeField(auto_now_add= True)
    updated_at          = models.DateTimeField(auto_now = True)

    object              = VariationManager()

    def __str__(self):
        return self.category_value

carts/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.http import  HttpResponse
from store.models import Product, VariationProduct
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser

def _cart_id(request):
    cart_id = request.session.session_key
    if not cart_id :
        cart_id = request.session.create()
    return cart_id


def add_cart(request, product_id):
    product = Product.objects.get(id = product_id)
    product_variation = []
    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]
            try:
                variation = VariationProduct.object.get(product= product, category_name__iexact = key , category_value__iexact = value)
                # print(variation)
                product_variation.append(variation)
            except:
                pass
        
        try:
            if(request.user.is_authenticated):
                cart = Cart.objects.get(user= request.user)
            else:
                cart = Cart.objects.get(cart_id = _cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id = _cart_id(request))
            cart.save()
       
        is_cart_item_exist = CartItem.objects.filter(product = product, cart = cart).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product = product, cart = cart)
            ex_variation_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_variation_list.append(list(existing_variation))
                id.append(item.id)
            
            if product_variation in ex_variation_list:
                index = ex_variation_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product = product, id = item_id)
                item.quantity += 1
                item.save()
            else:
               
                cart_item = CartItem.objects.create(
                    product = product,
                    quantity = 1,
                    cart = cart
                )
                if len(product_variation) > 0:
                    cart_item.variation.clear()
                    cart_item.variation.add(*product_variation)
                    cart_item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart
            )
            if len(product_variation) > 0:
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
                cart_item.save()
    return redirect('cart')
    

def delete_cart_quantity(request, cart_item_id, cart_id = 0):
    if request.user.is_authenticated:
        cart = Cart.objects.get(cart_id = cart_id)
    else:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    cart_item = CartItem.objects.get(id = cart_item_id, cart = cart)
    if cart_item.quantity > 1 : 
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart') 

def remove_cart_item(request, cart_item_id, cart_id = 0):
    if request.user.is_authenticated:
            cart = Cart.objects.get(cart_id = cart_id)
    else:
        cart = Cart.objects.get(cart_id = _cart_id(request))
    cart_item = CartItem.objects.get(id = cart_item_id, cart = cart)   
    cart_item.delete()
    return redirect('cart') 


# Create your views here.
def cart(request,quantity= 0, total = 0,  cart_item = None):
    tax = 0
    grand_total = 0
    cart_items = list()
    try:
        if request.user.is_authenticated:
            cart = Cart.objects.filter(user__id = request.user.id)
            for ct in cart:
                cart_item_data   = CartItem.objects.filter(cart = ct , is_active = True)
                cart_items      += cart_item_data 
                for cart_item in cart_item_data:
                    total       += ( cart_item.product.price * cart_item.quantity )
                    quantity    += cart_item.quantity
                    tax         = ( 2 * total ) /100
                    grand_total = total + tax
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart = cart , is_active = True)
            for cart_item in cart_items:
                total       += ( cart_item.product.price * cart_item.quantity )
                quantity    += cart_item.quantity
                tax         = ( 2 * total ) /100
                grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total' : total,
        'quantity' : quantity,
        'cart_items' : cart_items,
        'tax' : tax,
        'grand_total' : grand_total
    } 
    return render(request, 'store/cart.html', context)

@login_required(login_url= 'login')
def checkout(request,quantity= 0, total = 0,  cart_item = None):
    tax = 0
    grand_total = 0
    try:
        if request.user.is_authenticated:
            cart = Cart.objects.get(user__id = request.user.id)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart = cart , is_active = True)
        for cart_item in cart_items:
            total       += ( cart_item.product.price * cart_item.quantity )
            quantity    += cart_item.quantity
            tax         = ( 2 * total ) /100
            grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total' : total,
        'quantity' : quantity,
        'cart_items' : cart_items,
        'tax' : tax,
        'grand_total' : grand_total
    } 
    return render(request, 'store/checkout.html', context)

store/views.py
from django.shortcuts import render, get_object_or_404
from store.models import Product 
from category.models import Category
from carts.models import CartItem
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage
from carts.views import _cart_id
from django.db.models import Q
# Create your views here.
def show_store(request, category_slug = None):
    categories = None
    list_products = None
    if category_slug != None :
        categories = get_object_or_404(Category, slug = category_slug)
        list_products = Product.objects.filter(category = categories,is_available = True)
    else:
        list_products = Product.objects.all().filter(is_available = True).order_by('id')

    paginator = Paginator(list_products, 6 )
    page_num  = request.GET.get('page')
    products_by_page = paginator.get_page(page_num)
    context = { 'products' : products_by_page, 'product_count' : list_products.count()}
    return render( request, 'store/store.html', context)

def product_detail(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug = category_slug, slug = product_slug )
        in_cart = CartItem.objects.filter(cart__cart_id = _cart_id(request), product = product).exists()
    except Exception as e:
        raise e
    context = {'product' : product, 'in_cart' : in_cart}
    return render(request, 'store/product_detail.html', context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET.get('keyword')
        if keyword:
            product = Product.objects.order_by('-created_at').filter(Q(description__icontains = keyword) | Q(product_name__icontains = keyword))
            product_count = product.count()
        context = {
            'products' : product,
            'product_count' : product_count
        }
    return render(request, 'store/store.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cart_items %}
        <div class="text-center">
            <h2>Your cart is empty</h2>
            <a href="{% url 'store' %}" class="btn btn-primary">Go Back to Store</a>
        </div>
    {% else %}
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
        {% for cart_item in cart_items %}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{cart_item.product.image.url}}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="{{cart_item.product.get_product_urls}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                    <p class="text-muted small">
                        {% if cart_item.variation.all %}
                        {% for item in cart_item.variation.all %}
                            {{item.category_name | capfirst}} : {{item.category_value | capfirst}} <br>
                        {% endfor %}
                        {% endif%}
                    </p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'delete_cart_quantity'  cart_item.id cart_item.cart.cart_id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{cart_item.quantity}}">
                                <div class="input-group-append">
                                    <form method="POST" action="{% url 'add_cart'  cart_item.product.id  %} ">
                                        {% csrf_token %}
                                        {% if cart_item.variation.all %}
                                        {% for item in cart_item.variation.all %}
                                            <input type="hidden" name="{{item.category_name | lower}}" value="{{item.category_value | lower}}" />
                                        {% endfor %}
                                        {% endif %}
                                        <input type="hidden" name="cart_id" value="{{cart_item.cart.cart_id | lower}}" />
                                        <button type="submit" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                    </form>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">${{cart_item.sub_total}}</var> 
                <small class="text-muted"> ${{cart_item.product.price}} each </small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'remove_cart_item' cart_item.id  cart_item.cart.cart_id %}" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
     <!-- {{cart_item } -->
    {% endfor %}
    </tbody>
    </table>
   
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    {% endif %}
    </div> <!-- container .//  -->
    </section>
{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="row">
        <aside class="col-lg-6">
    <div class="card">
        <article class="card-body">
            <header class="mb-4"><h4 class="card-title">Billing Address</h4></header>
        <form method="POST" action="{% url 'place_order'%}">
            {% csrf_token %}
                <div class="form-row">
                    <div class="col form-group">
                        <label>First name</label>
                        <input type="text" class="form-control" placeholder="First Name" name="first_name">
                    </div>
                    <div class="col form-group">
                        <label>Last name</label>
                        <input type="text" class="form-control" placeholder="Last Name" name="last_name">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" placeholder="Email Address" name="email">
                    </div>
                    <div class="col form-group">
                        <label>Phone Number</label>
                        <input type="text" class="form-control" placeholder="Phone number" name="phone">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Address Line1</label>
                        <input type="text" class="form-control" placeholder="Address Line1" name="address_line1">
                    </div>
                    <div class="col form-group">
                        <label>Address Line2</label>
                        <input type="text" class="form-control" placeholder="Address Line2" name="address_line2">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>City</label>
                        <input type="text" class="form-control" placeholder="City" name="city">
                    </div>
                    <div class="col form-group">
                        <label>State</label>
                        <input type="text" class="form-control" placeholder="State" name="state">
                    </div>
                    <div class="col form-group">
                        <label>Country</label>
                        <input type="text" class="form-control" placeholder="Country" name="country">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Pincode</label>
                        <input type="text" class="form-control" placeholder="Pincode number" name="pincode">
                    </div>
                </div>
                <div class="form-row">
                    <div class="col form-group">
                        <label>Order Note</label>
                        <textarea name="order_note" class="form-control" placeholder="Order Note"></textarea>
                    </div>
                </div>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-6">
    
            <div class="card">
                <table class="table table-borderless table-shopping-cart">
                    <thead class="text-muted">
                    <tr class="small text-uppercase">
                      <th scope="col">Product</th>
                      <th scope="col" width="120">Quantity</th>
                      <th scope="col" width="120">Price</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <figure class="itemside align-items-center">
                                <div class="aside"><img src="{{cart_item.product.image.url}}" class="img-sm"></div>
                                <figcaption class="info">
                                    <a href="{{cart_item.product.get_product_urls}}" class="title text-dark">{{cart_item.product.product_name}}</a>
                                    <p class="text-muted small">
                                        {% if cart_item.variation.all %}
                                        {% for item in cart_item.variation.all %}
                                            {{item.category_name | capfirst}} : {{item.category_value | capfirst}} <br>
                                        {% endfor %}
                                        {% endif%}
                                    </p>
                                </figcaption>
                            </figure>
                        </td>
                        <td> 
                            <!-- col.// -->
                                        <div class="col"> 
                                           {{cart_item.quantity}}
                                        </div> <!-- col.// -->
                        </td>
                        <td> 
                            <div class="price-wrap"> 
                                <var class="price">${{cart_item.sub_total}}</var> 
                                <small class="text-muted"> ${{cart_item.product.price}} each </small> 
                            </div> <!-- price-wrap .// -->
                        </td>
                    </tr>
                     <!-- {{cart_item } -->
                    {% endfor %}
                    </tbody>
                </table>
                <hr>
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                {% if user.id is None %}
                <a href="{% url 'login' %}" class="btn btn-primary btn-block"> Place Order </a>
                {% else %}
                <button type="submit" class="btn btn-primary btn-block"> Place Order </button>
                {% endif %}
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                </form>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    </div> <!-- container .//  -->
    </section>
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
    <article class="gallery-wrap"> 
        <div class="img-big-wrap">
           <a href="#"><img src="{{product.image.url}}"></a>
        </div> <!-- img-big-wrap.// -->
        
    </article> <!-- gallery-wrap .end// -->
            </aside>
            <main class="col-md-6 border-left">
              <form action="{% url 'add_cart' product.id  %}" method="POST">
    <article class="content-body">
    
    <h2 class="title">{{product.product_name}}</h2>
    
    <div class="mb-3"> 
        <var class="price h4">${{product.price}}</var> 
    </div> 
    
    <p>{{product.description}}</p>
    
    {% csrf_token %}
    <hr>
        <div class="row">
            <div class="item-option-select">
                <h6>Choose Color</h6>
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                  <select name="color" class="form-control" required>
                    <option selected value="" disabled>Select</option>
                    {% for i in product.variationproduct_set.colors %}
                    <option value="{{i.category_value | lower}}">{{i.category_value | capfirst}}</option>
                    {% endfor %}
                  </select>
                </div> 
            </div>
        </div> <!-- row.// -->
        <div class="row">
            <div class="item-option-select">
                <h6>Select Size</h6>
                <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                    <select name="size" class="form-control" required>
                      <option value="" selected disabled>Select</option>
                      {% for i in product.variationproduct_set.size %}
                      <option value="{{i.category_value | lower}}">{{i.category_value | capfirst}}</option>
                      {% endfor %}
                    </select>
                </div> 
            </div>
        </div> <!-- row.// -->
        <hr>
        {% if product.stock > 0 %}
        <button type="submit" class="btn  btn-primary"> 
          <span class="text">Add to cart</span> 
          <i class="fas fa-shopping-cart"></i>  
        </button>
      
        {% else %}
          <b>Product out of stock! </b>
      {% endif %}
    </article> <!-- product-info-aside .// -->
  </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        <header class="section-heading">
            <h3>Customer Reviews </h3>  
            
        </header>
    
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
                <div class="text">
                    <span class="date text-muted float-md-right">24.04.2020 </span>  
                    <h6 class="mb-1">Mike John </h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <p>
                    Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip
                </p>	
            </div>
        </article>
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}